### ISSUE TITLE
Missing/incorrect fee data

### ISSUE THREAD

**Issue by mononaut** [bitfeed-project/bitfeed#32]
#### Symptoms

- Fees and fee rates are missing or negative in the mouse-over info for transactions
- Transactions colored dark red in color-by-fee-rate mode
- API server logs show many `Failed to inflate input` and `:timeout` messages
- Most likely to occur immediately after a system update or device reboot on Umbrel or similar home node deployments

#### Diagnosis

When the API server receives a very high rate of new transaction events, the task queue used for fetching and processing transaction prevout data becomes saturated, leading to cascading timeouts.

In normal operation, the transaction rate never comes close to a fraction of this saturation threshold, but Bitcoin Core can send an overwhelming number of transaction events while 'catching up' after a restart, especially when there is mempool congestion.

On home node devices like Umbrel, this is exacerbated by low powered hardware and high CPU demand from other services following a device reboot or system update.

#### Short Term Mitigation

Can be resolved by restarting just the Bitfeed server *after* Bitcoin Core has fully resynchronized (this can take a while).

On Umbrel/Citadel nodes:

- Manually:
    - Uninstall Bitfeed
        - Go to the 'Apps' page on your node dashboard
        - Click 'Edit'
        - Uninstall Bitfeed
    - Reinstall from the App Store page
- Via SSH:
    - On Citadel, run `docker restart bitfeed-api-1`
    - On Umbrel, run `docker restart bitfeed_api_1`
    
The issue is likely to re-occur after rebooting the node or restarting Bitcoin Core.

#### Long Term Fix

- Increase prevout expansion throughput.
  - Process prevout expansions asynchronously
  - Use pooled RPC connections
  - Increase Task and RPC timeouts
- Apply backpressure to reduce load during transaction floods
  - Fail prevout expansion tasks faster
  - Fall back to skipping prevout expansion during new transaction floods
- Recover from RPC/prevout expansion failures

**Comment by AaronDewes** [comment]
Regarding your Citadel instructions: Unlike Umbrel, we use docker-compose v2 (Umbrel uses v1). v2 generates container names with `-` instead of `_`, so the correct command for Citadel would be `docker restart bitfeed-api-1`

**Comment by mononaut** [comment]
thanks, I'll fix that now
