### ISSUE TITLE
Bitcoin Core pruned also works

### ISSUE THREAD

**Issue by SergioGlorias** [bitfeed-project/bitfeed#49]
I know that in the server's `README.md` it says not to use a pruned node with the bitfeed
But from what I can see, it works without problems apart from the part that:
- gives error 404 (on console) to get transaction information that has no information
- when searching for a block already pruned it appears "server error" under the search and 404 in the console
- in the mempool appears orange blocks without data (some of them have information, they are normal) after the block is generated they are colored and go to the block

this is the bitfeed view with node pruned:
![image](https://user-images.githubusercontent.com/9739913/169815353-a3df62a2-e46b-4101-a795-5e87bbfa5531.png)

**Comment by mononaut** [comment]
Thanks for documenting this!

It looks like we could officially support using a pruned node with a few changes 🚀

We just need:
 - Nicer error messages when searching for pruned blocks/transactions
 - Calculate fees for transactions with pruned ancestors (missing fee data is why some squares are orange).
 - Handle missing inputs when drawing the transaction details diagram
 
I've opened a new issue to track progress on implementing this #50
